---
deployment:
  tasks:
    - /bin/mkdir -p /home/mxafnahk/pendiwebid
    - /bin/cp -R app /home/mxafnahk/pendiwebid/
    - /bin/cp -R system /home/mxafnahk/pendiwebid/
    - /bin/cp composer.json /home/mxafnahk/pendiwebid/
    - /bin/cp composer.lock /home/mxafnahk/pendiwebid/
    - /bin/mkdir -p /home/mxafnahk/pendiwebid/writable/cache /home/mxafnahk/pendiwebid/writable/logs /home/mxafnahk/pendiwebid/writable/session /home/mxafnahk/pendiwebid/writable/uploads /home/mxafnahk/pendiwebid/writable/debugbar
    - /bin/cp -R public/. /home/mxafnahk/public_html/
